version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: elbek
      MONGO_INITDB_ROOT_PASSWORD: elbek